import Link from "next/link";
import "./globals.css";
import Header from "./component/header"
import Footer from "./component/footer"




export const metadata = {
  title: "jin_han app",
  description: "Generated by create jin_han app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>



  );
}
